name: Hello world!

on:
  push:
    branches:
      - master


jobs:
  hello_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  now_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Now it is
        run: |
          date
  
  list_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Directory content
        run: |
          ls -l