name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: npm install 
        run: npm install  
      
      - name: lint
        run: npm run eslint
      
      - name: build
        run: npm run build
      
      - name: test
        run: npm run test
      
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kaapon-pokedex"
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
          healthcheck: "https://kaapon-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch





# Manual Bumping: Any commit message that includes #major, #minor, #patch, or #none will trigger the
# respective version bump. If two or more are present, the highest-ranking one will take precedence. 
# If #none is contained in the commit message, it will skip bumping regardless DEFAULT_BUMP.

# Automatic Bumping: If no #major, #minor or #patch tag is contained in the commit messages, it will 
# bump whichever DEFAULT_BUMP is set to (which is minor by default). Disable this by setting DEFAULT_BUMP to none.